### ISSUE TITLE
Excesively rigid

### ISSUE THREAD

**Issue by LuiggyMadrid** [MicrosoftDocs/cpp-docs.es-es#46]
This warning arises in millions of lines in my VS2010 C/C++ code.
For example:
int n=5, kd=6;
double ab = new double [n*(kd+1)];
But, why? n, kd and 1 are ints, not __int64!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a3bb5405-5b75-6e6f-dcad-bda6a41665b8
* Version Independent ID: b806753e-dbf6-4ba5-ec3c-bd0ae9f10e10
* Content: [C26451](https://docs.microsoft.com/es-es/cpp/code-quality/c26451?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DES-ES%26k%3Dk(C26451)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/c26451.md](https://github.com/MicrosoftDocs/cpp-docs.es-es/blob/live/docs/code-quality/c26451.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @LuiggyMadrid
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@LuiggyMadrid 
The analyzer doesn't look at the values you've assigned when it's looking for arithmetic overflow. It's only looking for the possibility. Two `int` values can easily overflow an `int` when multiplied. 
If you can verify that the expressions flagged by code analysis can't overflow, then the best solution might be to turn off this warning. Otherwise, you must either test each multiplication for overflow, or apply a cast. If the expressions are like your example and the values are constants, then you could also precompute them.

**Comment by CeciAc** [comment]
Hello, @LuiggyMadrid 
Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 
We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 

Microsoft DOCS International Team
